### ISSUE TITLE
Privacy cookie widget

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-privacy#1]
A widget to provide the privacy text.

```php
luya\privacy\CookieHint::widget();
```

The cookie should work out of the box, with inline css for absolut position etc. even a message file with default texts should be available but with option to override.

options:

+ message
+ element (an array to full configure the html element)
+ css: turn off or override defaults

Full config could look like:

```php
luya\privacy\CookieHint::widget([
    'message' => 'text ...'
    'element' => ['tag' => 'p', 'class' => 'alert alert-info'
]);
```

**Comment by JohnnyMcWeed** [comment]
It should now be working out of the box with the configuration proposed in the PR Readme. (The block is not yet working)
As a next step it is maybe a good idea if there is a possibility for different opt-in levels, so that  a user can have the choice between e.g.:
- Required cookies (cookies which are really needed for a site to work)
- Analytical cookies
- Marketing cookies

**Comment by nadar** [comment]
Maybe we should delete the block to keep it easy for the moment.

**Comment by JohnnyMcWeed** [comment]
I think with the suggested adoptions it should then be working. Deleting the block is ok at the moment.. (I'll open up another issue as it is something we should really include..)

**Comment by nadar** [comment]
yes, please create a new issue where we can discuss the functions and requirements of such a block. thanks

**Comment by JohnnyMcWeed** [comment]
Just tried to use it.. Configuring buttons doesn't seem to be working anymore..

**Comment by JohnnyMcWeed** [comment]
Sorry, wrong button^^
Just tried to use it again.. buttons didn't work with custom configuration.. (E.g. setting the button title)

**Comment by nadar** [comment]
the decline button is deactivated by default, configure decline button works fine. but yes if you want to configure the accept button you have to provided at least the same properties.

**Comment by nadar** [comment]
@JohnnyMcWeed could you please provide more infos or directly add a unit test which is failing so we could maybe close this issue?

**Comment by JohnnyMcWeed** [comment]
It works now as expected. I just had the old code in place and didn't see that I now need to use all properties instead of single override.. Therefore I think it can be closed. If I'll face any problems I'll make an issue/pr.
