### ISSUE TITLE
Cookie container class

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-privacy#9]
Currently we're adding the styles e.g. through `$css` param and/or project css.

It would maybe make sense, if the widget's CSS class is adjustable aswell. 
Like this we could then use e.g. Bootstrap's fixed bottom class or whatever and it would directly be styled in our default colors.

**Comment by nadar** [comment]
Could you make a concret example in the code? What css code you are not able to adjust? It would be easy to add an options array to pass to the elements creation - if needed.

**Comment by JohnnyMcWeed** [comment]
It's not the problem that I am not able to adjust the code. I was more thinking about the case with bootstrap, where e.g. the following could become handy:
```
<?= PrivacyWidget::widget([
            'message' => Yii::t('app', 'widget.we_use_cookies.message'),
            'acceptButton' => [
               'tag' => 'a',
               'href' => '?acceptCookies=1',
               'class' => 'btn btn-primary',
               'content' => Yii::t('app', 'widget.we_use_cookies.accept'),
            ],
            'css' => '',
            'cssContainer' => 'fixed-bottom bg-light'
    ]) ?>
```
So this part would directly give the styling.
```
'css' => '',
'cssContainer' => 'fixed-bottom bg-light'
```

**Comment by nadar** [comment]
seems like a valid case, would like to send a PR for this property?

**Comment by JohnnyMcWeed** [comment]
Sure I can do that, but completely busy for the next 3-4 weeks.
After that I'll adjust it and send the PR if that's ok :)
